server:
  port: 9020

spring:
  application:
    name: CONFIG-SERVER
  profiles:
   active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SivasankarThalavai/config-server
          clone-on-start: true
    