server:
  port: 9011

spring:
  application:
    name: DEPARTMENT-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/
  h2:
    console:
      enabled: true
      settings:
       web-allow-others: true
    
logging:
  file:
    name: department-service-log